# Generated by Django 4.0.4 on 2022-06-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ingregient_ingredient_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingrediant',
        ),
    ]
